"""add reviewrid on document

Revision ID: 0a8df555c271
Revises: 7fbca08cc29a
Create Date: 2026-05-12 13:10:50.302654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8df555c271'
down_revision: Union[str, Sequence[str], None] = '7fbca08cc29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outliner_documents', sa.Column('reviewer_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_outliner_documents_reviewer_id'), 'outliner_documents', ['reviewer_id'], unique=False)
    op.create_foreign_key(None, 'outliner_documents', 'users', ['reviewer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outliner_documents', type_='foreignkey')
    op.drop_index(op.f('ix_outliner_documents_reviewer_id'), table_name='outliner_documents')
    op.drop_column('outliner_documents', 'reviewer_id')
    # ### end Alembic commands ###
