"""add is category and order

Revision ID: 23264f32c6b1
Revises: f2a38547111c
Create Date: 2026-01-21 14:55:31.157652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23264f32c6b1'
down_revision: Union[str, Sequence[str], None] = 'f2a38547111c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outliner_documents', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('outliner_documents', sa.Column('category', sa.String(), nullable=True))
    op.alter_column('outliner_documents', 'total_segments',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('outliner_documents', 'annotated_segments',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('outliner_documents', 'progress_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('outliner_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('outliner_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('outliner_segments', 'is_annotated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('outliner_segments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('outliner_segments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outliner_segments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('outliner_segments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('outliner_segments', 'is_annotated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('outliner_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('outliner_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('outliner_documents', 'progress_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('outliner_documents', 'annotated_segments',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('outliner_documents', 'total_segments',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('outliner_documents', 'category')
    op.drop_column('outliner_documents', 'order')
    # ### end Alembic commands ###
