"""add resolve on rejection

Revision ID: 28d6360e19ce
Revises: f8a1c2d3e4b5
Create Date: 2026-04-14 10:34:09.973161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d6360e19ce'
down_revision: Union[str, Sequence[str], None] = 'f8a1c2d3e4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment_rejections', sa.Column('resolved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segment_rejections', 'resolved')
    # ### end Alembic commands ###
