"""add reviewer edit

Revision ID: 3cb9ee4dd4e6
Revises: c4d9e2f1a8b0
Create Date: 2026-04-14 16:06:13.697525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb9ee4dd4e6'
down_revision: Union[str, Sequence[str], None] = 'c4d9e2f1a8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
