"""add edit and span detail of author and title

Revision ID: 49d5bb3ff894
Revises: 889ad7f5157c
Create Date: 2026-03-27 10:00:21.560853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d5bb3ff894'
down_revision: Union[str, Sequence[str], None] = '889ad7f5157c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outliner_segments', sa.Column('title_span_start', sa.Integer(), nullable=True))
    op.add_column('outliner_segments', sa.Column('title_span_end', sa.Integer(), nullable=True))
    op.add_column('outliner_segments', sa.Column('updated_title', sa.String(), nullable=True))
    op.add_column('outliner_segments', sa.Column('author_span_start', sa.Integer(), nullable=True))
    op.add_column('outliner_segments', sa.Column('author_span_end', sa.Integer(), nullable=True))
    op.add_column('outliner_segments', sa.Column('updated_author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outliner_segments', 'updated_author')
    op.drop_column('outliner_segments', 'author_span_end')
    op.drop_column('outliner_segments', 'author_span_start')
    op.drop_column('outliner_segments', 'updated_title')
    op.drop_column('outliner_segments', 'title_span_end')
    op.drop_column('outliner_segments', 'title_span_start')
    # ### end Alembic commands ###
