"""add supplied title 2

Revision ID: 889ad7f5157c
Revises: fe9e2fca500f
Create Date: 2026-03-10 15:22:19.041589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889ad7f5157c'
down_revision: Union[str, Sequence[str], None] = 'fe9e2fca500f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outliner_segments', sa.Column('is_supplied_title', sa.Boolean(), nullable=True))
    op.drop_column('outliner_segments', 'supplied_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outliner_segments', sa.Column('supplied_title', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('outliner_segments', 'is_supplied_title')
    # ### end Alembic commands ###
