"""delete total

Revision ID: 8c3767f8dd81
Revises: 94c5c40cd3fb
Create Date: 2026-02-25 16:34:08.728787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c3767f8dd81'
down_revision: Union[str, Sequence[str], None] = '94c5c40cd3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outliner_documents', 'total_segments')
    op.drop_column('outliner_documents', 'annotated_segments')
    op.drop_column('outliner_documents', 'progress_percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outliner_documents', sa.Column('progress_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('outliner_documents', sa.Column('annotated_segments', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('outliner_documents', sa.Column('total_segments', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
