"""add is annotated

Revision ID: 9164e64b8695
Revises: e0f2ace4a63b
Create Date: 2026-01-20 10:46:12.240872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9164e64b8695'
down_revision: Union[str, Sequence[str], None] = 'e0f2ace4a63b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outliner_segments', sa.Column('is_attached', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outliner_segments', 'is_attached')
    # ### end Alembic commands ###
