"""add user comment on segment

Revision ID: 9f379ddaa280
Revises: 16b9c8abd52c
Create Date: 2026-01-21 16:16:11.424261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f379ddaa280'
down_revision: Union[str, Sequence[str], None] = '16b9c8abd52c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outliner_segments', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outliner_segments', 'comment')
    # ### end Alembic commands ###
