"""update outline to save ai toc

Revision ID: aa2cd2e55aff
Revises: 49d5bb3ff894
Create Date: 2026-03-30 17:39:42.294276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2cd2e55aff'
down_revision: Union[str, Sequence[str], None] = '49d5bb3ff894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outliner_documents', sa.Column('ai_toc_entries', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outliner_documents', 'ai_toc_entries')
    # ### end Alembic commands ###
