"""add comment as json

Revision ID: c573471e3f61
Revises: 9f379ddaa280
Create Date: 2026-01-22 17:51:49.911368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c573471e3f61'
down_revision: Union[str, Sequence[str], None] = '9f379ddaa280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL requires USING clause to cast VARCHAR to JSON
    op.execute("""
        ALTER TABLE outliner_segments 
        ALTER COLUMN comment TYPE JSON 
        USING CASE 
            WHEN comment IS NULL OR comment = '' THEN NULL
            ELSE comment::json
        END
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert JSON back to VARCHAR using ::text cast
    op.execute("""
        ALTER TABLE outliner_segments 
        ALTER COLUMN comment TYPE VARCHAR 
        USING CASE 
            WHEN comment IS NULL THEN NULL
            ELSE comment::text
        END
    """)
    # ### end Alembic commands ###
