"""add outline

Revision ID: e0f2ace4a63b
Revises: f1201d6863ad
Create Date: 2026-01-19 16:07:33.428221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f2ace4a63b'
down_revision: Union[str, Sequence[str], None] = 'f1201d6863ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create outliner_documents table
    op.create_table(
        'outliner_documents',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('filename', sa.String(), nullable=True),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('total_segments', sa.Integer(), nullable=True),
        sa.Column('annotated_segments', sa.Integer(), nullable=True),
        sa.Column('progress_percentage', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outliner_documents_user_id'), 'outliner_documents', ['user_id'], unique=False)
    
    # Create outliner_segments table
    op.create_table(
        'outliner_segments',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('document_id', sa.String(), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('segment_index', sa.Integer(), nullable=False),
        sa.Column('span_start', sa.Integer(), nullable=False),
        sa.Column('span_end', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('author', sa.String(), nullable=True),
        sa.Column('title_bdrc_id', sa.String(), nullable=True),
        sa.Column('author_bdrc_id', sa.String(), nullable=True),
        sa.Column('parent_segment_id', sa.String(), nullable=True),
        sa.Column('is_annotated', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['document_id'], ['outliner_documents.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['parent_segment_id'], ['outliner_segments.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outliner_segments_document_id'), 'outliner_segments', ['document_id'], unique=False)
    op.create_index('ix_outliner_segments_document_index', 'outliner_segments', ['document_id', 'segment_index'], unique=False)
    op.create_index('ix_outliner_segments_span', 'outliner_segments', ['document_id', 'span_start', 'span_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outliner_segments_span', table_name='outliner_segments')
    op.drop_index('ix_outliner_segments_document_index', table_name='outliner_segments')
    op.drop_index(op.f('ix_outliner_segments_document_id'), table_name='outliner_segments')
    op.drop_table('outliner_segments')
    op.drop_index(op.f('ix_outliner_documents_user_id'), table_name='outliner_documents')
    op.drop_table('outliner_documents')
    # ### end Alembic commands ###
