"""add submit_count

Revision ID: e661979c6628
Revises: 3cb9ee4dd4e6
Create Date: 2026-04-16 16:34:34.353599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e661979c6628'
down_revision: Union[str, Sequence[str], None] = '3cb9ee4dd4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outliner_documents', sa.Column('submit_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outliner_documents', 'submit_count')
    # ### end Alembic commands ###
