"""update brandname to unique

Revision ID: f1201d6863ad
Revises: 42f086ba58bd
Create Date: 2026-01-09 14:25:11.481381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1201d6863ad'
down_revision: Union[str, Sequence[str], None] = '42f086ba58bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tenants_brand_name'), 'tenants', ['brand_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_brand_name'), table_name='tenants')
    # ### end Alembic commands ###
