"""add status

Revision ID: f2a38547111c
Revises: 9164e64b8695
Create Date: 2026-01-20 11:17:12.394086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a38547111c'
down_revision: Union[str, Sequence[str], None] = '9164e64b8695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outliner_documents', sa.Column('status', sa.String(), nullable=True))
    op.add_column('outliner_segments', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outliner_segments', 'status')
    op.drop_column('outliner_documents', 'status')
    # ### end Alembic commands ###
