"""add supplied title

Revision ID: fe9e2fca500f
Revises: 7f20d8332733
Create Date: 2026-03-10 14:54:09.900993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9e2fca500f'
down_revision: Union[str, Sequence[str], None] = '7f20d8332733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outliner_segments', sa.Column('supplied_title', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outliner_segments', 'supplied_title')
    # ### end Alembic commands ###
