"""
Compatibility facade for repository access (`outliner_repo.*`).

Implementation is split across ``document``, ``segment``, ``segment_rejection``,
``segment_review``, and ``analytics``.
"""
from outliner.repository.analytics import (
    get_annotator_performance_breakdown,
    get_dashboard_stats,
)
from outliner.repository.document import (
    bdrc_modified_by_from_document,
    delete_document,
    fetch_document_by_filename,
    fetch_document_by_id,
    fetch_document_workspace_row,
    fetch_documents_by_ids,
    get_document_progress,
    increment_document_submit_count,
    insert_document,
    list_completed_document_ids_all_segments_checked,
    list_documents,
    map_document_id_to_filename,
    replace_segments_and_ai_toc,
    reset_segments,
    set_document_status_and_refresh,
    update_document_content,
    allow_user_to_assign_volume,
)
from outliner.repository.segment import (
    add_segment,
    add_segment_flush,
    bulk_segment_operations_execute,
    commit_and_refresh_segments,
    commit_session,
    count_non_approved_segments,
    delete_orm_entity,
    delete_segment_and_reindex,
    document_has_any_segment,
    execute_bump_segment_indices_after,
    fetch_following_segments_by_index,
    fetch_following_segments_excluding_ids,
    fetch_segments_by_ids,
    fetch_segments_by_ids_for_document,
    fetch_segments_for_bulk_update,
    fetch_segments_ordered_by_ids,
    get_segment_by_pk,
    get_segment_comments_list,
    get_segment_plain,
    get_segment_with_rejections,
    insert_segment,
    insert_segments_bulk,
    list_segments,
    max_segment_index,
    merge_segments_persist,
    refresh_entity,
    reject_segments_bulk,
    segment_list_for_document,
    update_segment_comment_persist,
    update_segment_status_persist,
    add_segment_comment_persist,
    delete_segment_comment_persist,
)
from outliner.repository.segment_review import (
    _norm_segment_text,
    apply_segment_review_metadata,
    apply_segment_review_title_author_tracking,
)
from outliner.repository.segment_rejection import (
    apply_rejection_to_segment,
    get_segment_rejection_count,
    latest_rejection_notice_by_document_ids,
    latest_rejection_reason_for_orm_segment,
    latest_rejection_resolved_for_orm_segment,
    latest_rejection_reviewer_for_orm_segment,
    latest_rejection_row_per_segment_subquery,
    mark_latest_rejection_resolved,
    rejection_counts_reasons_reviewers_by_segment_ids,
    update_segment_with_rejection_fields,
)
